# GNUCash Transaction Analyzer Configuration
# This is a sample configuration file showing all available options

# Specify which credit card accounts to analyze
# Use the exact account paths as shown by: ./gpython3 list_accounts.py <gnucash_file>
credit_card_accounts:
  - "Credit Cards: Citi Costo Visa"
  - "Credit Cards: Fidelity Visa"
  # Uncomment and modify the accounts you want to analyze:
  # - "Liabilities: Credit Cards: Chase Freedom"
  # - "Liabilities: Credit Cards: American Express"
  # - "Liabilities: Credit Cards: Discover"
  
  # Example format (adjust to match your account structure):
  # - "Credit Cards: Visa"
  # - "Credit Cards: MasterCard"

# Optional: Specify date range for analysis
date_range:
  # start_date: "2023-01-01"  # YYYY-MM-DD format
  # end_date: "2024-12-31"    # YYYY-MM-DD format

# Optional: Rule generation settings
rule_settings:
  minimum_transactions: 2      # Minimum transactions needed to create a rule
  confidence_threshold: 0.3    # Minimum confidence score for rules (0.0-1.0)
  fuzzy_similarity: 0.8       # Similarity threshold for fuzzy merchant matching (0.0-1.0)

# Usage Instructions:
# 1. First, list your accounts: ./gpython3 list_accounts.py ~/gnc/accounts.gnucash --credit-cards-only
# 2. Copy the account paths you want to analyze into the credit_card_accounts section above
# 3. Uncomment the accounts by removing the '# ' prefix
# 4. Optionally adjust the date range and rule settings
# 5. Run: ./gpython3 analyze_transactions.py ~/gnc/accounts.gnucash --config analyze_config.yaml
