name: gnc
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - ipython
  - tabulate
  - pyyaml
  - langgraph 
  - langchain-openai 
  - langchain-community 
  - tavily-python
  - langchain-tavily

